apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  namespace: default
spec:
  containers:
  - name: apache
    image: skyning/mycv-app:fbf3500d6b2f63ca6e7e826605032ccc19ec5015
    ports:
    - containerPort: 80

